/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrabble;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author estuardoarevalo
 */
public class frmGraph extends javax.swing.JPanel {

    private String imagePath;
    private Image image;
    
    /**
     * Creates new form frmGraph
     */
    public frmGraph(String _imagePath) {
        imagePath = _imagePath;
        image = new ImageIcon(imagePath).getImage();
        initComponents();
        this.setPreferredSize(new Dimension(image.getWidth(null), image.getHeight(null)));
        
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        //Image image = new ImageIcon(imagePath).getImage();
        g.drawImage(image, 0, 0, this);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
